name: Index notifly docs on Typesense
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  index_docs:
    name: Index notifly docs on Typesense
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "scripts"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Index documents
        run: chmod +x ./index_docs.sh && ./index_docs.sh
